-- ============================================================
-- GT HOMES Holiday Resort — Seed Data
-- File: database/seed.sql
--
-- Run AFTER schema.sql.
-- Creates the default admin user.
-- Password must be set via PHP:
--   echo password_hash('YourStrongPassword', PASSWORD_DEFAULT);
-- Then update the hash below.
--
-- IMPORTANT: Change the password hash before production deployment.
-- ============================================================

USE gt_homes;

-- ──────────────────────────────────────
-- Default Admin User
-- Replace the hash with a real bcrypt hash generated by:
--   php -r "echo password_hash('YourPassword', PASSWORD_DEFAULT);"
-- ──────────────────────────────────────
INSERT IGNORE INTO `users` (`name`, `email`, `password_hash`, `role`, `is_active`)
VALUES (
  'GT HOMES Admin',
  'admin@gthomes.lk',
  '$2y$12$PLACEHOLDER_REPLACE_WITH_REAL_BCRYPT_HASH_BEFORE_USE',
  'admin',
  1
);

-- ──────────────────────────────────────
-- Gallery Categories (starter)
-- ──────────────────────────────────────
INSERT IGNORE INTO `gallery_categories` (`name`, `slug`, `sort_order`) VALUES
  ('Memories',         'memories',         1),
  ('Special Memories', 'special-memories', 2),
  ('Resort',           'resort',           3);
